--- #YAML:1.0
name: Workflow
version: 0.05
license: perl
distribution_type: module
requires:
  Class::Accessor: 0.18
  DBD::Mock: 0.1
  DateTime: 0.15
  DateTime::Format::Strptime: 1
  Exception::Class: 1.1
  Log::Dispatch: 2
  Log::Log4perl: 0.34
  Test::More: 0.41
  XML::Simple: 2
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Workflow:
    file: lib/Workflow.pm
    version: 1.15
  Workflow::Action:
    file: lib/Workflow/Action.pm
    version: 1.05
  Workflow::Action::InputField:
    file: lib/Workflow/Action/InputField.pm
    version: 1.08
  Workflow::Base:
    file: lib/Workflow/Base.pm
    version: 1.05
  Workflow::Condition:
    file: lib/Workflow/Condition.pm
    version: 1.04
  Workflow::Condition::HasUser:
    file: lib/Workflow/Condition/HasUser.pm
    version: 1.03
  Workflow::Config:
    file: lib/Workflow/Config.pm
    version: 1.08
  Workflow::Config::Perl:
    file: lib/Workflow/Config/Perl.pm
    version: 1.01
  Workflow::Config::XML:
    file: lib/Workflow/Config/XML.pm
    version: 1.01
  Workflow::Context:
    file: lib/Workflow/Context.pm
    version: 1.03
  Workflow::Exception:
    file: lib/Workflow/Exception.pm
    version: 1.07
  Workflow::Factory:
    file: lib/Workflow/Factory.pm
    version: 1.12
  Workflow::History:
    file: lib/Workflow/History.pm
    version: 1.07
  Workflow::Persister:
    file: lib/Workflow/Persister.pm
    version: 1.08
  Workflow::Persister::DBI:
    file: lib/Workflow/Persister/DBI.pm
    version: 1.14
  Workflow::Persister::DBI::AutoGeneratedId:
    file: lib/Workflow/Persister/DBI/AutoGeneratedId.pm
    version: 1.05
  Workflow::Persister::DBI::ExtraData:
    file: lib/Workflow/Persister/DBI/ExtraData.pm
    version: 1.04
  Workflow::Persister::DBI::SequenceId:
    file: lib/Workflow/Persister/DBI/SequenceId.pm
    version: 1.03
  Workflow::Persister::File:
    file: lib/Workflow/Persister/File.pm
    version: 1.09
  Workflow::Persister::RandomId:
    file: lib/Workflow/Persister/RandomId.pm
    version: 1.02
  Workflow::Persister::SPOPS:
    file: lib/Workflow/Persister/SPOPS.pm
    version: 1.06
  Workflow::Persister::UUID:
    file: lib/Workflow/Persister/UUID.pm
    version: 1.02
  Workflow::State:
    file: lib/Workflow/State.pm
    version: 1.05
  Workflow::Validator:
    file: lib/Workflow/Validator.pm
    version: 1.04
  Workflow::Validator::HasRequiredField:
    file: lib/Workflow/Validator/HasRequiredField.pm
    version: 1.03
  Workflow::Validator::InEnumeratedType:
    file: lib/Workflow/Validator/InEnumeratedType.pm
    version: 1.03
  Workflow::Validator::MatchesDateFormat:
    file: lib/Workflow/Validator/MatchesDateFormat.pm
generated_by: Module::Build version 0.21
